#!/bin/bash
# 📥 BACKUP: APP -> PC
PACKAGE_NAME="com.sans.finance"
SNAPSHOT_NAME="sans_finance_db_snapshot.sqlite"

echo "💾 Extracting Database Snapshot from Phone..."
# This pulls the file YOU generated by clicking 'Sync' in the app
adb pull /sdcard/Download/$SNAPSHOT_NAME .

echo "✅ Backup complete! Your snapshot is now in: ./$SNAPSHOT_NAME"
